apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  description: Workloads applicatifs
  sourceRepos:
    - https://github.com/mouameng/gitops-lab.git
  destinations:
    - name: workload-dev
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
