apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  description: Composants d'infrastructure des clusters geres
  sourceRepos:
    - https://github.com/mouameng/gitops-lab.git
    - https://kubernetes.github.io/ingress-nginx
    - https://metallb.github.io/metallb
    - https://bitnami.github.io/sealed-secrets
  destinations:
    - name: workload-dev
      namespace: '*'
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
