apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEKzCCApOgAwIBAgIUa5HcojnITv1BAwyAdchQQFtUl3IwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSR2l0T3BzIExhYiBSb290IENBMB4XDTI2MTAwNjE5NDkw
    MloXDTM2MTAwMzE5NDkwMlowHTEbMBkGA1UEAwwSR2l0T3BzIExhYiBSb290IENB
    MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAj85hLyz7pwFVQPcnGwfJ
    Mh/oQNUfZ+6+JqAVmRj/FXy7V0kOyzVGz6eveOpHU4Y9EaOCqQtlDTD9lag3rQnj
    PFRQB/uexRKOdvc9jK2bc/4dPUun+zBMvKet6QTwoauC3lvhhBz72EfAvXunlMYA
    m/nksHvKN6ytGJ9EmnkQ5OfusRyW8NUK71qYoZ0c32d92Adv2G8Z/Xisq0c05VOy
    ZXs82Sjn8Xyyepm8utUW+gB/mvc6YUY4JpZXhfSiSGTrccIw9SxNJSlLMG2jpVYT
    nkfRCM2DxbzgienT1fneXtE1r6ZaVVzgTBjQU4/qwhFRt+oiYM+YjatF/G+16QgB
    WW6m8CqNLFoLQAXaTztj66oVJR7lNShApAhvKoHsjn2r3nhox7XURlA7vR/BHAVU
    s0c1ZNvzb5g5qybHq7KgLPgspYd4RRAt/XUaoTyy+rwkd+zHiJTuc46Q4/XFEvvc
    ypdqB6+VpFSkq7ng7T3xev/lU/tRZ0yZH1u+KfpCQ/VZAgMBAAGjYzBhMB0GA1Ud
    DgQWBBTnXOR0P9O9yLzNs6weLfKOU4FOEDAfBgNVHSMEGDAWgBTnXOR0P9O9yLzN
    s6weLfKOU4FOEDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjANBgkq
    hkiG9w0BAQsFAAOCAYEAXB04WLvFQPwvZl7Vv5y5PEkz5is3NDR5hb+1WFqA0Gm4
    WaxMTBwLPiCtr5+Uq/aBuYWBbcZdqIMuriI19GYQlJhbNh4EXSoWOtgOuaJjO4Ru
    CR84FVUcvJNFKVHY7LeGW+bggKb42Y8ZmfG4hGiu/0TFi75AVLOEN7ojir1mou/d
    SCWhT4Xy3fq4IDej/7xucCLXPpYH2aJ7ISBHQMY/oWbhm+4cBw8B1cWCbnhZ5IZu
    AIZvSq4X8F/tFCbX3Lkc0QN8yC/DZDSEbNLQ+waBCyI+F6jwgAPSYI7gKqXo/PCV
    WwjSU0YXJUpGFpVp4/FP5ZlGAGugq563R6c40nXFP1dBjrfOzoy6QraKAuhLY0lz
    nYf3vcDQdqFYcjAuplqqqj3sb6cQIfyrZWxx5/SAcHjSizOBzR2NJGSwTquJpwzT
    NqzhLh+5adL2h+wLCTqGkCExKxY6qwrJZ14/bVnbB3xqBsL3eaRwPyhEMlr3Mnyk
    Vxr5rHnX5VaruqhENXoj
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: gitea-runner-ca
  namespace: gitea-runner
