---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-registration
  namespace: gitea-runner
spec:
  encryptedData:
    token: AgAWZcMRIH9+9mjKuOR2odHkhKYEqEctYq+FcAbEhDyOC+wrMM4hIysp4/QaQokuRP5TsYrhve2+sS+9GeMuwH4e7oWaEFToHcNJKc4yvvZM3at5vEsgQV46RymBrnF4YPNVjegTzjMfHzFzJJIb9rrxn5jurXMGfkrlt5g1WfQz/mg+Pt61IT25fmJXD31gyiWIqWpKdh13ka9QTU5Z1VFtJiT1W5wtWEik/HQgM9rsJMQqNBwNysRHTAmeCNVfD1kpoo82P+79wJIYO9UIJ7newtf5GKE5whAxvF2qYD/xNxnUfmzOcWyrAgkgOndCK0PYnf6bRIiX7qZVFLT+LlwB9hVPPpTpDfwYWMY1wrzTWWu+fQmkt/mwXJrfypn3XghfTcL8Aic8M+hZgixk4ANGoaFK5AU8VwC4Y2TKxnhiwefB3izVG5f4aSh1cMRUaIvCe90YxSNxtDPjYCNtFFCdTy/8lUBTxRCdPAt4abLWKngVx20k4ZEdpydPJKoVMoBBk5oFwWkTXDAgSRqpAtAJJbA6YqTEsxdVb1XlroAsFPNY/FXhMaQqVVOggpF+zMkFRuOdDT0KbsNX+kWChFo1oWrphaM6ZYGY7/SYFYtOe0GPXwr78s8tH0ymk3n+1dIg77gCkkW9zs/edni+o4VzoWBeTWfjS9RA+KZ5WuDjbAr9jxmw3O1OqfYLzUqOW4MD/ednpv+vTexJEJccyyow35Bkip7QXl1TOIdUMZPWyI4XV1bEPa9m
  template:
    metadata:
      name: gitea-runner-registration
      namespace: gitea-runner
