apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: gitea-local
  namespace: gitea
spec:
  secretName: gitea-local-tls
  issuerRef:
    name: gitops-lab-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - gitea.local
