valkey-cluster:
  enabled: false
valkey:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  storageClass: standard
  size: 2Gi

gitea:
  admin:
    existingSecret: gitea-admin-secret
    passwordMode: initialOnlyNoReset
  config:
    server:
      DOMAIN: gitea.local
      ROOT_URL: https://gitea.local/
      SSH_DOMAIN: gitea.local
    database:
      DB_TYPE: sqlite3
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
