apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.health.cert-manager.io_Certificate: |
    hs = {}
    hs.status = "Progressing"
    hs.message = "Waiting for certificate"

    if obj.status ~= nil and obj.status.conditions ~= nil then
      for _, condition in ipairs(obj.status.conditions) do
        if condition.type == "Issuing" and condition.status == "True" then
          hs.status = "Progressing"
          hs.message = condition.message
          return hs
        end
      end

      for _, condition in ipairs(obj.status.conditions) do
        if condition.type == "Ready" then
          hs.message = condition.message

          if condition.status == "True" then
            hs.status = "Healthy"
          elseif condition.status == "False" then
            hs.status = "Degraded"
          end

          return hs
        end
      end
    end

    return hs
