apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-local
  namespace: argocd

spec:
  secretName: argocd-local-tls

  issuerRef:
    name: gitops-lab-ca-issuer
    kind: ClusterIssuer

  dnsNames:
    - argocd.local
