# argocd/applications/cert-manager-config.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "-25"

spec:
  project: infrastructure

  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/platform/infrastructure-devops.git
    targetRevision: main
    path: infrastructure/cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
