apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048-dev
  namespace: argocd
spec:
  project: applications

  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/platform/infrastructure-devops.git
    targetRevision: HEAD
    path: applications/games/2048/overlays/dev

  destination:
    name: workload-dev
    namespace: game-2048

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
