apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-external
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/gitops-lab.git
    targetRevision: main
    path: applications/gitea
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
