apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/mouameng/gitops-lab.git
    targetRevision: HEAD
    path: argocd/infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true