apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  project: infrastructure

  source:
    repoURL: https://github.com/mouameng/gitops-lab.git
    targetRevision: HEAD
    path: infrastructure/metallb

  destination:
    name: workload-dev
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true