apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workload-prod-cluster
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: applications

  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/gitops-lab.git
    targetRevision: main
    path: applications/clusters/workload-prod

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
